import type { AIModel } from '@/types';

export const aiModels: AIModel[] = [
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openrouter',
    description: 'OpenAI\'s flagship model — fast, smart, great for full Roblox systems.',
    premium: true,
    context_window: 128000,
    tags: ['openai', 'reasoning', 'premium'],
  },
  {
    id: 'claude-opus',
    name: 'Claude Opus',
    provider: 'openrouter',
    description: 'Anthropic\'s most capable model — excels at complex scripting and architecture.',
    premium: true,
    context_window: 200000,
    tags: ['anthropic', 'premium', 'architecture'],
  },
  {
    id: 'claude-sonnet',
    name: 'Claude Sonnet',
    provider: 'openrouter',
    description: 'Best price-performance balance for daily Roblox development.',
    premium: false,
    context_window: 200000,
    tags: ['anthropic', 'balanced', 'prototyping'],
  },
  {
    id: 'claude-3.5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'openrouter',
    description: 'Anthropic\'s upgraded workhorse — excels at long-form code generation and deep reasoning.',
    premium: false,
    context_window: 200000,
    tags: ['anthropic', 'reasoning', 'coding'],
  },
  {
    id: 'claude-3.5-haiku',
    name: 'Claude 3.5 Haiku',
    provider: 'openrouter',
    description: 'Blazing fast Anthropic model — ideal for quick iterations and lightweight tasks.',
    premium: false,
    context_window: 200000,
    tags: ['anthropic', 'fast', 'lightweight'],
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openrouter',
    description: 'Lightweight and fast — ideal for quick scripts and iterations.',
    premium: false,
    context_window: 128000,
    tags: ['openai', 'fast', 'lightweight'],
  },
  {
    id: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    provider: 'openrouter',
    description: 'OpenAI\'s previous-gen flagship — strong reasoning with broad knowledge cutoff.',
    premium: false,
    context_window: 128000,
    tags: ['openai', 'reasoning', 'coding'],
  },
  {
    id: 'grok-3',
    name: 'Grok-3',
    provider: 'openrouter',
    description: 'xAI\'s latest — creative and unfiltered for unique game mechanics.',
    premium: false,
    context_window: 131072,
    tags: ['xai', 'creative', 'experimental'],
  },
  {
    id: 'gemini-flash',
    name: 'Gemini Flash',
    provider: 'openrouter',
    description: 'Google\'s fast model — great for rapid prototyping.',
    premium: false,
    context_window: 1048576,
    tags: ['google', 'fast', 'prototyping'],
  },
  {
    id: 'gemini-1.5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'openrouter',
    description: 'Google\'s most capable model — massive context window for large codebases.',
    premium: true,
    context_window: 2000000,
    tags: ['google', 'premium', 'large-context'],
  },
  {
    id: 'deepseek-v2.5',
    name: 'DeepSeek V2.5',
    provider: 'openrouter',
    description: 'Strong open-source model — excellent at both math and code generation.',
    premium: false,
    context_window: 128000,
    tags: ['deepseek', 'open-source', 'coding'],
  },
  {
    id: 'llama-3.1-405b',
    name: 'Llama 3.1 405B',
    provider: 'openrouter',
    description: 'Meta\'s largest open model — near-frontier performance for complex tasks.',
    premium: true,
    context_window: 131072,
    tags: ['meta', 'open-source', 'premium', 'large'],
  },
  {
    id: 'qwen-2.5-72b',
    name: 'Qwen 2.5 72B',
    provider: 'openrouter',
    description: 'Alibaba\'s powerful open model — strong reasoning and multilingual support.',
    premium: false,
    context_window: 131072,
    tags: ['alibaba', 'open-source', 'reasoning'],
  },
  {
    id: 'mixtral-8x22b',
    name: 'Mixtral 8x22B',
    provider: 'openrouter',
    description: 'Mistral\'s MoE model — efficient inference with high-quality output.',
    premium: false,
    context_window: 65536,
    tags: ['mistral', 'open-source', 'efficient', 'moe'],
  },
  {
    id: 'mistral',
    name: 'Mistral Small',
    provider: 'openrouter',
    description: 'Lightweight Mistral model for straightforward scripting tasks.',
    premium: false,
    context_window: 32000,
    tags: ['mistral', 'open-source', 'efficient'],
  },
  {
    id: 'txmo',
    name: 'TXMO',
    provider: 'local',
    description: 'Premium local AI model. Ultra-fast inference, no external API calls. Exclusive to premium subscribers.',
    premium: true,
    context_window: 16000,
    tags: ['local', 'premium', 'fast', 'exclusive'],
  },
];

export function getModelById(modelId: string) {
  return aiModels.find((model) => model.id === modelId) ?? null;
}
