import axios from 'axios';
import { aiModels, getModelById } from './ai-models';
import { insertUsage, generateId, now } from './db';
import type { AIResponse, AIModel } from '@/types';

const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;

const greetings = ['hi', 'hello', 'hey', 'sup', 'yo', 'whats up', 'how are you', 'good morning', 'good evening'];
const isGreeting = (s: string) => greetings.some(g => s === g || s.startsWith(g + ' ') || s.startsWith(g + '?'));

const sampleFallback = (model: AIModel, prompt: string) => {
  const p = prompt.toLowerCase().trim();

  // Natural conversation
  if (isGreeting(p)) {
    const responses = [
      "Hey there! 👋 Ready to build something awesome in Roblox? Tell me what you want to create - a combat system, a GUI, a game mechanic, anything!",
      "Hello! 🥥 What Roblox system should we build today? Scripts, UI, VFX, or an entire game mode?",
      "Hey! 🌴 I'm here to help you code. What kind of Roblox experience are we making?",
      "Hi! 👋 Got a Roblox project in mind? Describe what you want and I'll generate the code!",
    ];
    return responses[Math.floor(Math.random() * responses.length)];
  }

  if (p.includes('who are you') || p.includes('what are you') || p.includes('what can you')) {
    return "I'm Coconut AI 🥥 - your Roblox development assistant. I can generate:\n\n• Combat systems (damage, hitboxes, weapons)\n• UI/GUI frameworks (menus, HUDs, buttons)\n• Movement systems (walk, dash, jump, speed)\n• Game mechanics (leaderboards, currencies, shops)\n• VFX and lighting systems\n• Full game modes\n\nJust tell me what you want to build!";
  }

  if (p.includes('thanks') || p.includes('thank you')) {
    return "You're welcome! 🥥 Want me to build anything else for your Roblox game?";
  }

  // Code generation prompts
  if (p.includes('combat') || p.includes('fight') || p.includes('damage') || p.includes('sword') || p.includes('weapon') || p.includes('attack') || p.includes('enemy') || p.includes('health')) {
    return `-- Combat System Generated by ${model.name}
-- Prompt: ${prompt}

local CombatService = {}

function CombatService.dealDamage(target, damage)
\tlocal humanoid = target:FindFirstChildOfClass("Humanoid")
\tif humanoid then
\t\thumanoid:TakeDamage(damage)
\t\treturn true
\tend
\treturn false
end

function CombatService.createHitbox(character, range)
\tlocal root = character:FindFirstChild("HumanoidRootPart")
\tif not root then return end
\tlocal params = RaycastParams.new()
\tparams.FilterDescendantsInstances = {character}
\tparams.FilterType = Enum.RaycastFilterType.Blacklist
\tlocal direction = root.CFrame.LookVector * range
\tlocal result = workspace:Raycast(root.Position, direction, params)
\treturn result
end

function CombatService.createProjectile(startPos, direction, speed, damage, owner)
\tlocal projectile = Instance.new("Part")
\tprojectile.Size = Vector3.new(1, 1, 1)
\tprojectile.Anchored = true
\tprojectile.CanCollide = false
\tprojectile.BrickColor = BrickColor.new("Bright red")
\tprojectile.Position = startPos

\tlocal bodyVelocity = Instance.new("BodyVelocity")
\tbodyVelocity.Velocity = direction * speed
\tbodyVelocity.MaxForce = Vector3.new(1, 1, 1) * math.huge
\tbodyVelocity.Parent = projectile

\tprojectile.Parent = workspace

\tcoroutine.wrap(function()
\t\ttask.wait(5)
\t\tprojectile:Destroy()
\tend)()

\tprojectile.Touched:Connect(function(hit)
\t\tlocal humanoid = hit.Parent:FindFirstChildOfClass("Humanoid")
\t\tif humanoid and humanoid.Parent ~= owner then
\t\t\thumanoid:TakeDamage(damage)
\t\t\tprojectile:Destroy()
\t\tend
\tend)

\treturn projectile
end

return CombatService`;
  }
  if (p.includes('gui') || p.includes('ui') || p.includes('screen') || p.includes('button') || p.includes('frame') || p.includes('menu') || p.includes('hud') || p.includes('dashboard')) {
    return `-- UI System Generated by ${model.name}
-- Prompt: ${prompt}

local function createFrame(name, parent, size, position, color, transparency)
\tlocal frame = Instance.new("Frame")
\tframe.Name = name
\tframe.Parent = parent
\tframe.Size = size or UDim2.new(0, 200, 0, 100)
\tframe.Position = position or UDim2.new(0.5, -100, 0.5, -50)
\tframe.BackgroundColor3 = color or Color3.fromRGB(30, 30, 40)
\tframe.BackgroundTransparency = transparency or 0
\tframe.BorderSizePixel = 0
\treturn frame
end

local function createButton(name, parent, size, position, text, color)
\tlocal btn = Instance.new("TextButton")
\tbtn.Name = name
\tbtn.Parent = parent
\tbtn.Size = size or UDim2.new(0, 150, 0, 40)
\tbtn.Position = position or UDim2.new(0, 0, 0, 0)
\tbtn.Text = text or "Button"
\tbtn.TextColor3 = Color3.fromRGB(255, 255, 255)
\tbtn.TextSize = 16
\tbtn.Font = Enum.Font.GothamSemibold
\tbtn.BackgroundColor3 = color or Color3.fromRGB(20, 184, 166)
\tbtn.BorderSizePixel = 0
\treturn btn
end

local screenGui = Instance.new("ScreenGui")
screenGui.Name = "CoconutUI"
screenGui.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")

local mainFrame = createFrame("MainFrame", screenGui, UDim2.new(0, 400, 0, 500), UDim2.new(0.5, -200, 0.5, -250), Color3.fromRGB(25, 25, 35))
local title = Instance.new("TextLabel")
title.Size = UDim2.new(1, -20, 0, 40)
title.Position = UDim2.new(0, 10, 0, 10)
title.Text = "Game Menu"
title.TextColor3 = Color3.fromRGB(255, 255, 255)
title.TextSize = 22
title.Font = Enum.Font.GothamBold
title.BackgroundTransparency = 1
title.Parent = mainFrame

local playBtn = createButton("PlayBtn", mainFrame, UDim2.new(0, 200, 0, 45), UDim2.new(0.5, -100, 0, 80), "Play", Color3.fromRGB(20, 184, 166))
playBtn.MouseButton1Click:Connect(function() print("Play button clicked!") end)

print("UI Created by Coconut AI")`;
  }
  if (p.includes('move') || p.includes('walk') || p.includes('run') || p.includes('speed') || p.includes('character') || p.includes('dash') || p.includes('jump') || p.includes('sprint')) {
    return `-- Movement System Generated by ${model.name}
-- Prompt: ${prompt}

local MovementService = {}

function MovementService.setWalkSpeed(character, speed)
\tlocal humanoid = character:FindFirstChildOfClass("Humanoid")
\tif humanoid then
\t\thumanoid.WalkSpeed = speed
\tend
end

function MovementService.setJumpPower(character, power)
\tlocal humanoid = character:FindFirstChildOfClass("Humanoid")
\tif humanoid then
\t\thumanoid.JumpPower = power
\tend
end

function MovementService.createDash(character, distance, duration)
\tlocal root = character:FindFirstChild("HumanoidRootPart")
\tif not root then return end
\tlocal humanoid = character:FindFirstChildOfClass("Humanoid")
\tif humanoid then humanoid.WalkSpeed = distance / duration end
\ttask.wait(duration)
\tif humanoid then humanoid.WalkSpeed = 16 end
end

function MovementService.createDoubleJump(character)
\tlocal humanoid = character:FindFirstChildOfClass("Humanoid")
\tif not humanoid then return end
\tlocal jumped = false
\thumanoid.Jumped:Connect(function()
\t\tif jumped then return end
\t\tjumped = true
\t\ttask.wait(0.3)
\t\tjumped = false
\tend)
end

function MovementService.createSprint(character, sprintSpeed, key)
\tlocal userInput = game:GetService("UserInputService")
\tlocal humanoid = character:FindFirstChildOfClass("Humanoid")
\tif not humanoid then return end
\tlocal normalSpeed = humanoid.WalkSpeed
\tuserInput.InputBegan:Connect(function(input)
\t\tif input.KeyCode == key or key == nil and input.KeyCode == Enum.KeyCode.LeftShift then
\t\t\thumanoid.WalkSpeed = sprintSpeed
\t\tend
\tend)
\tuserInput.InputEnded:Connect(function(input)
\t\tif input.KeyCode == key or key == nil and input.KeyCode == Enum.KeyCode.LeftShift then
\t\t\thumanoid.WalkSpeed = normalSpeed
\t\tend
\tend)
end

return MovementService`;
  }
  if (p.includes('leaderboard') || p.includes('currency') || p.includes('shop') || p.includes('money') || p.includes('coins') || p.includes('score') || p.includes('points') || p.includes('economy')) {
    return `-- Economy System Generated by ${model.name}
-- Prompt: ${prompt}

local EconomyService = {}
local playerData = {}

function EconomyService:getData(player)
\tif not playerData[player.UserId] then
\t\tplayerData[player.UserId] = { coins = 0, gems = 0, experience = 0, level = 1, inventory = {} }
\tend
\treturn playerData[player.UserId]
end

function EconomyService:addCoins(player, amount)
\tlocal data = self:getData(player)
\tdata.coins += amount
\treturn data.coins
end

function EconomyService:spendCoins(player, amount)
\tlocal data = self:getData(player)
\tif data.coins >= amount then
\t\tdata.coins -= amount
\t\treturn true
\tend
\treturn false
end

function EconomyService:addExperience(player, amount)
\tlocal data = self:getData(player)
\tdata.experience += amount
\tlocal needed = data.level * 100
\twhile data.experience >= needed do
\t\tdata.experience -= needed
\t\tdata.level += 1
\t\tneeded = data.level * 100
\tend
\treturn data.level
end

function EconomyService:addItem(player, itemName, quantity)
\tlocal data = self:getData(player)
\tdata.inventory[itemName] = (data.inventory[itemName] or 0) + (quantity or 1)
end

function EconomyService:hasItem(player, itemName, quantity)
\tlocal data = self:getData(player)
\treturn (data.inventory[itemName] or 0) >= (quantity or 1)
end

return EconomyService`;
  }
  return `-- Generated by ${model.name}
-- Prompt: ${prompt}

local module = {}

function module.setup()
\tprint("Coconut AI generating: ${prompt.replace(/'/g, "\\\\'")}")
\t-- Add your custom logic here
end

return module`;
};

async function requestOpenAI(prompt: string, model: AIModel): Promise<AIResponse> {
  if (!OPENAI_API_KEY) {
    return { model: model.name, provider: model.provider, output: sampleFallback(model, prompt), usage: { prompt_tokens: prompt.length, completion_tokens: 64, total_tokens: prompt.length + 64 } };
  }
  const response = await axios.post('https://api.openai.com/v1/chat/completions', {
    model: model.id, messages: [{ role: 'user', content: prompt }],
    temperature: 0.2, max_tokens: 800,
  }, {
    headers: { Authorization: `Bearer ${OPENAI_API_KEY}`, 'Content-Type': 'application/json' },
  });
  const output = response.data.choices?.[0]?.message?.content ?? '';
  const usage = response.data.usage ?? { prompt_tokens: 0, completion_tokens: 0, total_tokens: 0 };
  return { model: model.name, provider: model.provider, output, usage };
}

async function requestAnthropic(prompt: string, model: AIModel): Promise<AIResponse> {
  if (!ANTHROPIC_API_KEY) {
    return { model: model.name, provider: model.provider, output: sampleFallback(model, prompt), usage: { prompt_tokens: prompt.length, completion_tokens: 64, total_tokens: prompt.length + 64 } };
  }
  const response = await axios.post('https://api.anthropic.com/v1/messages', {
    model: model.id, messages: [{ role: 'user', content: prompt }], max_tokens: 800,
  }, {
    headers: { 'x-api-key': ANTHROPIC_API_KEY, 'anthropic-version': '2023-06-01', 'Content-Type': 'application/json' },
  });
  const output = response.data.content?.[0]?.text ?? '';
  const u = response.data.usage || {};
  const usage = { prompt_tokens: u.input_tokens || 0, completion_tokens: u.output_tokens || 0, total_tokens: (u.input_tokens || 0) + (u.output_tokens || 0) };
  return { model: model.name, provider: model.provider, output, usage };
}

async function requestGeneric(prompt: string, model: AIModel): Promise<AIResponse> {
  return { model: model.name, provider: model.provider, output: sampleFallback(model, prompt), usage: { prompt_tokens: prompt.length, completion_tokens: 64, total_tokens: prompt.length + 64 } };
}

export async function generateAIResponse(
  prompt: string, modelId: string, userId: string, role: string,
  subscriptionActive: boolean, subscriptionExpiresAt: string | null,
  workspaceName = 'Coconut AI Workspace', projectId?: string, projectName?: string
): Promise<AIResponse> {
  const selectedModel = getModelById(modelId);
  if (!selectedModel) throw new Error('Unsupported model selected');

  if (selectedModel.premium) {
    const valid = subscriptionActive && (!subscriptionExpiresAt || new Date(subscriptionExpiresAt) > new Date());
    if (!valid && role !== 'admin') throw new Error('This model is reserved for premium subscribers.');
  }

  let result: AIResponse;
  switch (selectedModel.provider) {
    case 'openai': result = await requestOpenAI(prompt, selectedModel); break;
    case 'anthropic': result = await requestAnthropic(prompt, selectedModel); break;
    default: result = await requestGeneric(prompt, selectedModel); break;
  }

  insertUsage({
    id: generateId(), user_id: userId, type: 'ai_generation', value: result.usage.total_tokens,
    meta: JSON.stringify({ model: selectedModel.id, provider: selectedModel.provider, prompt_length: prompt.length, project_id: projectId, project_name: projectName }),
    created_at: now(),
  });

  const { createOrUpdateWorkspaceSession } = await import('./workspace');
  const existing = await createOrUpdateWorkspaceSession(userId, workspaceName, { metadata: {} });
  if (existing) {
    const existingMeta = existing.metadata || {};
    const mergedHistory = [
      ...(Array.isArray(existingMeta.history) ? existingMeta.history : []),
      { role: 'user' as const, text: prompt, timestamp: now() },
      { role: 'assistant' as const, text: result.output, timestamp: now() },
    ].slice(-20);

    await createOrUpdateWorkspaceSession(userId, workspaceName, {
      status: 'active', last_synced_at: now(),
      metadata: {
        ...existingMeta, last_prompt: prompt, last_response: result.output.slice(0, 300),
        model: selectedModel.name, provider: selectedModel.provider,
        history: mergedHistory, active_project_id: projectId, active_project_name: projectName,
      },
    });
  }

  return result;
}

export function getAvailableModels() {
  return aiModels;
}
